# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
        build:
          docker:
            - image: maciejmalecki/c64libci:0.1.6

          working_directory: ~/repo

          environment:
            JVM_OPTS: -Xms256m -Xmx768m
            TERM: dumb

          steps:
            - checkout
            - attach_workspace:
                at: ./artifacts
            - run: mkdir out
            - run: mkdir work
            - run: ./gradlew build --stacktrace
            - run: exomizer sfx sys src/rex.prg -o work/rex.prg
            - run: c1541 -format "trex64,21" d64 work/rex.d64 && c1541 -attach work/rex.d64 -write work/rex.prg trex64
            - run: cp src/extra/readme.md work/00readme.md
            - run: cd work && ls -al
            - run: zip out/trex.zip work/*
            - run: tar czf out/trex.tgz work/*
            - run: cd out && ls -al
            - persist-to-workspace:
                root: .
                paths:
                    - out


        publish:
          docker:
            - image: cibuilds/github:0.10
          steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                name: "Publish PRG on GitHub"
                command: |
                    ls ./artifacts/out
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/out

workflows:
    version: 2
    commit:
        jobs:
            - build

    publish:
        jobs:
            - build:
                filters:
                    branches:
                        ignore:
                            - /.*/
                    tags:
                        only:
                            - /^([0-9]+)\.([0-9]+)\.([0-9]+).*$/
            - publish:
                filters:
                    branches:
                        ignore:
                            - /.*/
                    tags:
                        only:
                            - /^([0-9]+)\.([0-9]+)\.([0-9]+).*$/
                requires:
                    - build
