# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
        build:
          docker:
            - image: maciejmalecki/c64libci:0.1.4

          working_directory: ~/repo

          environment:
            JVM_OPTS: -Xms256m -Xmx768m
            TERM: dumb

          steps:
            - checkout
            - attach_workspace:
                at: ./artifacts
            - run: mkdir out
            - run: ./gradlew build
            - run: cp src/rex.prg out
            - run: cd out && ls -al
            - persist-to-workspace:
                root: .
                paths:
                    - out

        crunch:
          docker:
            - image: maciejmalecki/c64libci:0.1.4
          steps:
            - attach_workspace:
                at: ./artifacts
            - run: git clone https://bitbucket.org/magli143/exomizer.git && cd exomizer && git checkout 3.1.1
            - run: cd exomizer/src && make build && ls -al
            - run: mkdir ./artifacts/pub
            - run: exomizer/src/exomizer sfx sys ./artifacts/out/rex.prg -o ./artifacts/pub/rex.prg
            - run: c1541 -format "trex64,21" d64 ./artifacts/pub/rex.d64 && c1541 -attach ./artifacts/pub/rex.d64 -write ./artifacts/pub/rex.prg trex64
            - run: cd ./artifacts/pub && ls -al
            - persist-to-workspace:
                root: ./artifacts
                paths:
                    - pub

        publish:
          docker:
            - image: cibuilds/github:0.10
          steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                name: "Publish PRG on GitHub"
                command: |
                    ls ./artifacts/pub
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/pub

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
                            - develop
                            - preview
                    tags:
                        only:
                            - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/
            - crunch:
                requires:
                    - build
            - publish:
                filters:
                    branches:
                        ignore:
                            - master
                            - develop
                            - preview
                    tags:
                        only:
                            - /^([0-9]+)\.([0-9]+)\.([0-9]+)$/
                requires:
                    - build
                    - crunch
